### ISSUE TITLE
Error in IE8

### ISSUE THREAD

**Issue by philippkuehn** [rodneyrehm/viewport-units-buggyfill#46]
Hey, I'm getting an error in IE8. This breaks all my javascript :)
I'm using version 0.5.1.

![bildschirmfoto 2015-03-26 um 17 38 02](https://cloud.githubusercontent.com/assets/2500670/6851417/2f0b485c-d3df-11e4-85c6-b9e7df0faf94.png)

**Comment by rodneyrehm** [comment]
I've failed getting an [IE8 VM](https://www.modern.ie/en-us/virtualization-tools#downloads) to run so I could try this myself… Please clone the repository and check if the error occurs with [index.html](https://github.com/rodneyrehm/viewport-units-buggyfill/blob/master/index.html).

**Comment by philippkuehn** [comment]
Yes, I'm getting a blank screen here.
In IE9 everything is fine.

![bildschirmfoto 2015-03-28 um 20 42 47](https://cloud.githubusercontent.com/assets/2500670/6882596/190e1608-d58b-11e4-8109-0291ef174ece.png)

**Comment by rodneyrehm** [comment]
ok, I'll take another look at getting my IE8 VM working again. Maybe @zoltan-dulac has an idea in the meantime?

**Comment by zoltan-dulac** [comment]
Hey guys.

The only IE support is for 9 and up, since it fixes the buggy support of vh & vw. We should at the least look at getting rid of js errors and replace it with a friendly error message. We *could* look at support for IE8, but I don't see this as high priority since all my clients in the last year do not demand support for it.

Bottom line: right now, there is no IE8 support. Just 9+.

**Comment by philippkuehn** [comment]
Yes fully agree! Get rid of the errors is enough.

**Comment by rodneyrehm** [comment]
released in [0.5.2](https://github.com/rodneyrehm/viewport-units-buggyfill/releases/tag/v0.5.2)
