### ISSUE TITLE
Edge Support

### ISSUE THREAD

**Issue by jmorone** [rodneyrehm/viewport-units-buggyfill#60]
Apparently Edge *still* does not understand vmax. Just updating the regex at line 87 makes everything better!

if (!isBuggyIE) {
    isBuggyIE = !!navigator.userAgent.match(/Trident.*rv[ :]*11|2\./);
  }

**Comment by rodneyrehm** [comment]
I don't think that regular expressen is doing what you had hoped it does. Maybe this what you intended?

```js
isBuggyIE = !!navigator.userAgent.match(/Trident.rv[ :]1(1|2)./);
```

if so, please submit a PR.

**Comment by jmorone** [comment]
Ooops, that'd probably be the proper way to approach this. Pretty new to GitHub, so not quite sure the etiquette. And I'm not very experienced with regex, but it isn't working with parens. Not sure why not.

**Comment by rodneyrehm** [comment]
Well, knowing your way around github has become kind of essential these days. Use this opportunity to try things out.

---

The [original regex](https://github.com/rodneyrehm/viewport-units-buggyfill/blob/master/viewport-units-buggyfill.js#L71):

```js
isBuggyIE = !!navigator.userAgent.match(/Trident.*rv[ :]*11\./);
```

Your updated RegExp is not working, because you assumed the user agent string would be something containing `"Trident.rv 12."`, which [does not match reality](https://msdn.microsoft.com/en-us/library/hh869301%28v=vs.85%29.aspx). The following expression should catch that:

```js
isBuggyIE = !!navigator.userAgent.match(/Trident.*rv[ :]*11\.| Edge\/12\./);
```
